// import localFont from "next/font/local";
// import "./globals.css";
// import NavbarWrapper from "@/context/navbarwrapper";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <navbarwrapper/>
//         {children}
//       </body>
//     </html>
//   );
// }
// src/app/layout.js

import { Inter } from "next/font/google";
import "./globals.css"; // Adjust path if necessary
import NavbarWrapper from "../components/../context/navbarwrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Skill Capital Clone",
};

export default function RootLayout({ children }) {
  return (
    
      <html lang="en">
        <body className={inter.className}>
          <NavbarWrapper/>
          {children}
        </body>
      </html>
    
  );
}
